"""empty message

Revision ID: 27bb8aae8aad
Revises: 481c345d625f
Create Date: 2025-08-05 20:11:12.269554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bb8aae8aad'
down_revision: Union[str, None] = '481c345d625f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('lngt', sa.String(), nullable=False))
    op.drop_column('building', 'long')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('long', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('building', 'lngt')
    # ### end Alembic commands ###
