"""empty message

Revision ID: 317f360adf25
Revises: 27bb8aae8aad
Create Date: 2025-08-06 19:01:27.636113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317f360adf25'
down_revision: Union[str, None] = '27bb8aae8aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'lat',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(precision=15, decimal_return_scale=8),
               existing_nullable=False,
               postgresql_using='lat::real')
    op.alter_column('building', 'lngt',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(precision=15, decimal_return_scale=8),
               existing_nullable=False,
               postgresql_using='lat::real')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'lngt',
               existing_type=sa.Float(precision=15, decimal_return_scale=8),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('building', 'lat',
               existing_type=sa.Float(precision=15, decimal_return_scale=8),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
